apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube-m04
      containers:
        - name: flask-backend-container
          image: hamzaarshad10/backend:latest
          ports:
            - containerPort: 8080  # The port your Flask app is running on inside the container
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: flask-backend
  ports:
    - protocol: TCP
      port: 8080  # Expose the Flask app on port 80 externally (NodePort)
      targetPort: 8080  # The port your Flask app is listening on inside the container
  type: NodePort
